### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by pb1051** [tgorgdotcom/locast2plex#184]
I keep getting an error for line 1 column 1 when setting up a container in my environment in regards to credentials. I have reset my password to verify that it was not a special character issue. I continue to receive the error below each time I start the container. I can't find any of the same exact issues posted so I am asking for help.

`Initiating Locast2Plex v0.6.2,
Opening and Verifying Configuration File.,
/app/config/config.ini,
Loading Configuration File: /app/config/config.ini,
Tuner count set to 3,
Server is set to run on  127.0.0.1:6077,
UUID set to: UUID...,
Getting user location...,
Getting location via provided zipcode 77346,
Got location as Houston - DMA 618 - Lat\Lon 29.9945\-95.17749,
Logging into Locast using username EMAIL@gmail.com...,
Error in function login: Expecting value: line 1 column 1 (char 0),
Invalid Locast Login Credentials. Exiting...,`

**Comment by KipKasper** [comment]
I see this same issue when using override_zipcode or override_latitude & override_longitude and coming in from an IP that is not from that area.  Could be a second location check server side that is failing and the login function doesn't have a way to deal with it.

**Comment by kuryak1n** [comment]
I'm having same problem as OP.  Deleted override_zipcode in config.ini.  No change.

**Comment by kuryak1n** [comment]
I'm having same problem as OP.

**Comment by kuryak1n** [comment]
I'm having same problem as OP.  Deleted override_zipcode from config.ini.  No change.  Running in docker on Synology NAS.  Worked fine when NAS was running DSM 6.  Updated NAS to DSM 7 and now the container will not run.  Other containers run fine.


2021-08-06 05:32:52,stdout,Invalid Locast Login Credentials. Exiting...
2021-08-06 05:32:52,stdout,Error in function login: Forbidden
2021-08-06 05:32:52,stdout,Logging into Locast using username <redacted>...
2021-08-06 05:32:52,stdout,Got location as Dallas - DMA 623 - Lat\Lon 32.8248\-96.7498
2021-08-06 05:32:51,stdout,Got external IP <redacted>.
2021-08-06 05:32:51,stdout,Getting location via IP Address.
2021-08-06 05:32:51,stdout,Getting user location...
2021-08-06 05:32:51,stdout,UUID set to: <redacted>...
2021-08-06 05:32:51,stdout,No UUID found.  Generating one now...
2021-08-06 05:32:51,stdout,Server is set to run on  127.0.0.1:6077
2021-08-06 05:32:51,stdout,Tuner count set to 4
2021-08-06 05:32:51,stdout,Loading Configuration File: /app/config/config.ini
2021-08-06 05:32:51,stdout,/app/config/config.ini
2021-08-06 05:32:51,stdout,Opening and Verifying Configuration File.
2021-08-06 05:32:51,stdout,Initiating Locast2Plex v0.6.5

**Comment by enz1ey** [comment]
I'm seeing the same issue, also using override_zipcode myself. Any progress on the issue?

**Comment by kuryak1n** [comment]
> I'm seeing the same issue, also using override_zipcode myself. Any progress on the issue?

Fixed in v0.6.6.

https://github.com/tgorgdotcom/locast2plex/releases/tag/0.6.6

**Comment by beergeekdotcom** [comment]
Still getting this with 0.6.6

Getting user location...
Getting location via provided lat\lon coordinates.
Got location as San Francisco - DMA 807 - Lat\Lon 37.77723\-122.44773
Logging into Locast using username XXXX@XXXX.com...
Error in function login: Bad Request
Invalid Locast Login Credentials. Exiting...
